### ISSUE TITLE
Error running node server.js after npm install -d

### ISSUE THREAD

**Issue by freddy-daniel** [tdryer/Node-Whiteboard#2]
PS C:\Users\Freddy\Desktop\Node-Whiteboard> node server.js
Server listening on port 80.
TypeError: process.getuid is not a function
    at Server.<anonymous> (C:\Users\Freddy\Desktop\Node-Whiteboard\server.js:287:17)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by tdryer** [comment]
Sorry, this code has been unmaintained for seven years. It probably doesn't work anymore.
